[env:m5stack-core-esp32]
platform = espressif32
board = m5stack-core-esp32
framework = espidf
monitor_speed = 115200
upload_port = /dev/cu.usbserial-01CDD202
monitor_port = /dev/cu.usbserial-01CDD202
upload_speed = 921600
